### ISSUE TITLE
Does it work at first?

### ISSUE THREAD

**Issue by jomsdev** [jomsdev/my-github-bot#7]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
cacacaca

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
adfakjdflajf;a

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
dfajdsf;lakj;fla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

more bla bla bla

**Comment by jomsdev** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

**Comment by kafkasl** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

**Comment by kafkasl** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 2500.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f86f9

**Comment by kafkasl** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 25200.00 ANT: 25.00
Contract address: 0x3645fe42b1a744ad98cc032c22472388806f8

**Comment by kafkasl** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 25200.00 ANT: 25.00
Contract address: 0x3645fe42b1a74

**Comment by kafkasl** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 25200.00 ANT: 25.00
Contract address: 0x3645fe42b1a74
